services:
  db:
    image: postgres
    restart: no
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=DB
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/

  app:
    platform: linux/amd64
    depends_on:
      - db
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./app:/app 
    command: python3 /app/main.py 
    stdin_open: true
    tty: true

volumes:
  db:
    driver: tmpfs