# Project information
site_name: 2024.2-Avatar
site_url: https://2024.2-avatar.com
site_author: O Grupo
site_description: >-
  Repositório para o projeto de um jogo RPG baseado na série animada Avatar, desenvolvido na disciplina de Sistemas de Banco de Dados 1 na Universidade de Brasilia.


# Repository
repo_url: https://github.com/SBD1/2024.2-Avatar
repo_name: 2024.2-Avatar


# Configuration
docs_dir: docs
theme: 
  name: material
  language: pt-BR
  icon:
    repo: fontawesome/brands/github
  font: 
    text: Roboto
  favicon: assets/icon.svg
  logo: assets/icon.svg
  features:
    - navigation.instant
    - navigation.section
    - navigation.path
    - navigation.top
    - tabs
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Mudar para o modo escuro
      primary: deep blue
      accent: blue 
    - scheme: slate 
      toggle:
        icon: material/brightness-4
        name: Mudar para o modo claro
      primary: deep blue
      accent: blue






# Page tree
nav: 
  - Início: index.md
  - Diagrama Entidade Relacionamento:
    - Versão 01: DER/v1.md
  - Dicionário de Dados:
    - Versão 01: DD/v1.md
  - Modelo Relacional:
    - Versão 01: MR/v1.md
  - Apresentações:
    - Modulo 01: Apresentacoes/Modulo01.md


# Extensions
markdown_extensions:
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences